---
title: "MUPPITS Nasal Cell Type Gene Level Analysis"
author: "Elizabeth Whalen"
date: "10/19/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Read in Data

```{r readData}

dataDir <- "../data"
resultsDir <- "../results"

load(file=file.path(dataDir, "nasalVoom_374samples.RData"))
nasalDesign<-read.csv(file=file.path(dataDir, "nasalDesign_374samples.csv"))
nasalGS<-read.csv(file=file.path(dataDir, "nasalGeneSets_374samples.csv"), row.names=1)
assignGS<-read.csv(file=file.path(dataDir, "geneSetsByAssignedCell.csv"))

# make sure everything matches
all(colnames(nasalVoom)==nasalDesign$library.sampleId)
all(colnames(nasalVoom)==colnames(nasalGS))

# remove cases that are on steroids - remove any negative values in Days.between.Visit.and.CSteroid.Use
nasalDesignOrig<-nasalDesign
nasalVoomOrig<-nasalVoom
nasalGSorig<-nasalGS
remIndex<-which(nasalDesign$Days.between.Visit.and.CSteroid.Use < 0)
nasalDesign<-nasalDesign[-remIndex,]
nasalVoom<-nasalVoom[,-remIndex]
all(nasalDesign$library.sampleId==colnames(nasalVoom))
nasalGS<-nasalGS[,-remIndex]
all(nasalDesign$library.sampleId==colnames(nasalGS))

```

## Split By Cell Type

```{r cellType}

## Neutrophil
matchIndex<-match(assignGS$ensemblID[which(assignGS$cellType=="neutrophil")], rownames(nasalVoom))
sum(is.na(matchIndex))
matchIndex<-matchIndex[-which(is.na(matchIndex))]
nasalVoomNeut<-nasalVoom[matchIndex,]
dim(nasalVoomNeut)

nDesignAB<-nasalDesign[which(nasalDesign$Visit %in% c("Visit a","Visit b")),]
nVoomNeutAB<-nasalVoomNeut[,which(nasalDesign$Visit %in% c("Visit a","Visit b"))]
all(nDesignAB$library.sampleId==colnames(nVoomNeutAB))

nDesignAB$Case.or.Control.Status.Original<-factor(as.character(nDesignAB$Case.or.Control.Status.Original), levels=c("Control","Case"))
nDesignAB$Visit<-factor(as.character(nDesignAB$Visit), levels=c("Visit a","Visit b"))

curMM<-model.matrix(~Case.or.Control.Status.Original + Visit + libCounts + Nasal.Lymphocyte.Count + Nasal.Macrophage.Count + Nasal.Eosinophil.Count + Nasal.Squamous.Count + Nasal.Epithelial.Count + Viral.Type.at.Visit2, data=nDesignAB)
remIndex<-which(!(rownames(nDesignAB) %in% rownames(curMM)))
length(remIndex)
 
corfit<-duplicateCorrelation(nVoomNeutAB[,-remIndex], curMM, block=nDesignAB$Subject.Identifier.for.the.Study[-remIndex])
corfit$consensus
  
fitNeu<-lmFit(nVoomNeutAB[,-remIndex], curMM, block=nDesignAB$Subject.Identifier.for.the.Study[-remIndex], correlation=corfit$consensus)
fitNeu<-eBayes(fitNeu)

ttNeu<-topTable(fitNeu, coef=2, number=nrow(nVoomNeutAB), sort.by="p")

library(biomaRt)
mart<-useMart("ENSEMBL_MART_ENSEMBL",dataset="hsapiens_gene_ensembl", host="www.ensembl.org")
resultsBio<-getBM(attributes=c("ensembl_gene_id", "hgnc_symbol","gene_biotype"), filters="ensembl_gene_id", values=rownames(nasalVoom), mart=mart)

addSymbol<-function(topT, resultsBio)
{
	topT$hgnc_symbol<-""
	for (i in 1:nrow(topT))
	{
		topT$hgnc_symbol[i]<-as.character(resultsBio$hgnc_symbol[which(rownames(topT)[i]==resultsBio$ensembl_gene_id)[1]])
	}
	return(topT)
}

ttNeu<-addSymbol(ttNeu, resultsBio)
write.csv(ttNeu, file=file.path(resultsDir, "nasal_geneLevel_topTable_Neutrophil.csv"))


## Eosinophil
matchIndex<-match(assignGS$ensemblID[which(assignGS$cellType=="eosinophil")], rownames(nasalVoom))
sum(is.na(matchIndex))
matchIndex<-matchIndex[-which(is.na(matchIndex))]
nasalVoomEos<-nasalVoom[matchIndex,]
dim(nasalVoomEos)

nVoomEosAB<-nasalVoomEos[,which(nasalDesign$Visit %in% c("Visit a","Visit b"))]
all(nDesignAB$library.sampleId==colnames(nVoomEosAB))

curMM<-model.matrix(~Case.or.Control.Status.Original + Visit + libCounts + Nasal.Lymphocyte.Count + Nasal.Macrophage.Count + Nasal.Eosinophil.Count + Nasal.Squamous.Count + Nasal.Epithelial.Count + Viral.Type.at.Visit2, data=nDesignAB)
remIndex<-which(!(rownames(nDesignAB) %in% rownames(curMM)))
length(remIndex)
 
corfitEo<-duplicateCorrelation(nVoomEosAB[,-remIndex], curMM, block=nDesignAB$Subject.Identifier.for.the.Study[-remIndex])
corfitEo$consensus
  
fitEos<-lmFit(nVoomEosAB[,-remIndex], curMM, block=nDesignAB$Subject.Identifier.for.the.Study[-remIndex], correlation=corfitEo$consensus)
fitEos<-eBayes(fitEos)

ttEos<-topTable(fitEos, coef=2, number=nrow(nVoomEosAB), sort.by="p")

ttEos<-addSymbol(ttEos, resultsBio)
write.csv(ttEos, file=file.path(resultsDir, "nasal_geneLevel_topTable_Eosinophil.csv"))


## Epithelial
matchIndex<-match(assignGS$ensemblID[which(assignGS$cellType=="epithelial")], rownames(nasalVoom))
sum(is.na(matchIndex))
matchIndex<-matchIndex[-which(is.na(matchIndex))]
nasalVoomEpi<-nasalVoom[matchIndex,]
dim(nasalVoomEpi)

nVoomEpiAB<-nasalVoomEpi[,which(nasalDesign$Visit %in% c("Visit a","Visit b"))]
all(nDesignAB$library.sampleId==colnames(nVoomEpiAB))

curMM<-model.matrix(~Case.or.Control.Status.Original + Visit + libCounts + Nasal.Lymphocyte.Count + Nasal.Macrophage.Count + Nasal.Eosinophil.Count + Nasal.Squamous.Count + Nasal.Epithelial.Count + Viral.Type.at.Visit2, data=nDesignAB)
remIndex<-which(!(rownames(nDesignAB) %in% rownames(curMM)))
length(remIndex)
 
corfitEpi<-duplicateCorrelation(nVoomEpiAB[,-remIndex], curMM, block=nDesignAB$Subject.Identifier.for.the.Study[-remIndex])
corfitEpi$consensus
  
fitEpi<-lmFit(nVoomEpiAB[,-remIndex], curMM, block=nDesignAB$Subject.Identifier.for.the.Study[-remIndex], correlation=corfitEpi$consensus)
fitEpi<-eBayes(fitEpi)

ttEpi<-topTable(fitEpi, coef=2, number=nrow(nVoomEpiAB), sort.by="p")

ttEpi<-addSymbol(ttEpi, resultsBio)
write.csv(ttEpi, file=file.path(resultsDir, "nasal_geneLevel_topTable_Epithelial.csv"))


## Lymphocyte
matchIndex<-match(assignGS$ensemblID[which(assignGS$cellType=="lymphocyte")], rownames(nasalVoom))
sum(is.na(matchIndex))
#matchIndex<-matchIndex[-which(is.na(matchIndex))]
nasalVoomLym<-nasalVoom[matchIndex,]
dim(nasalVoomLym)

nVoomLymAB<-nasalVoomLym[,which(nasalDesign$Visit %in% c("Visit a","Visit b"))]
all(nDesignAB$library.sampleId==colnames(nVoomLymAB))

curMM<-model.matrix(~Case.or.Control.Status.Original + Visit + libCounts + Nasal.Lymphocyte.Count + Nasal.Macrophage.Count + Nasal.Eosinophil.Count + Nasal.Squamous.Count + Nasal.Epithelial.Count + Viral.Type.at.Visit2, data=nDesignAB)
remIndex<-which(!(rownames(nDesignAB) %in% rownames(curMM)))
length(remIndex)
 
corfitLym<-duplicateCorrelation(nVoomLymAB[,-remIndex], curMM, block=nDesignAB$Subject.Identifier.for.the.Study[-remIndex])
corfitLym$consensus
  
fitLym<-lmFit(nVoomLymAB[,-remIndex], curMM, block=nDesignAB$Subject.Identifier.for.the.Study[-remIndex], correlation=corfitLym$consensus)
fitLym<-eBayes(fitLym)

ttLym<-topTable(fitLym, coef=2, number=nrow(nVoomLymAB), sort.by="p")

ttLym<-addSymbol(ttLym, resultsBio)
write.csv(ttLym, file=file.path(resultsDir, "nasal_geneLevel_topTable_Lymphocyte.csv"))


## Macrophage
matchIndex<-match(assignGS$ensemblID[which(assignGS$cellType=="macrophage")], rownames(nasalVoom))
sum(is.na(matchIndex))
#matchIndex<-matchIndex[-which(is.na(matchIndex))]
nasalVoomMac<-nasalVoom[matchIndex,]
dim(nasalVoomMac)

nVoomMacAB<-nasalVoomMac[,which(nasalDesign$Visit %in% c("Visit a","Visit b"))]
all(nDesignAB$library.sampleId==colnames(nVoomMacAB))

curMM<-model.matrix(~Case.or.Control.Status.Original + Visit + libCounts + Nasal.Lymphocyte.Count + Nasal.Macrophage.Count + Nasal.Eosinophil.Count + Nasal.Squamous.Count + Nasal.Epithelial.Count + Viral.Type.at.Visit2, data=nDesignAB)
remIndex<-which(!(rownames(nDesignAB) %in% rownames(curMM)))
length(remIndex)
 
corfitMac<-duplicateCorrelation(nVoomMacAB[,-remIndex], curMM, block=nDesignAB$Subject.Identifier.for.the.Study[-remIndex])
corfitMac$consensus
  
fitMac<-lmFit(nVoomMacAB[,-remIndex], curMM, block=nDesignAB$Subject.Identifier.for.the.Study[-remIndex], correlation=corfitMac$consensus)
fitMac<-eBayes(fitMac)

ttMac<-topTable(fitMac, coef=2, number=nrow(nVoomMacAB), sort.by="p")

ttMac<-addSymbol(ttMac, resultsBio)
write.csv(ttMac, file=file.path(resultsDir, "nasal_geneLevel_topTable_Macrophage.csv"))


## Squamous
matchIndex<-match(assignGS$ensemblID[which(assignGS$cellType=="squamous")], rownames(nasalVoom))
sum(is.na(matchIndex))
matchIndex<-matchIndex[-which(is.na(matchIndex))]
nasalVoomSqu<-nasalVoom[matchIndex,]
dim(nasalVoomSqu)

nVoomSquAB<-nasalVoomSqu[,which(nasalDesign$Visit %in% c("Visit a","Visit b"))]
all(nDesignAB$library.sampleId==colnames(nVoomSquAB))

curMM<-model.matrix(~Case.or.Control.Status.Original + Visit + libCounts + Nasal.Lymphocyte.Count + Nasal.Macrophage.Count + Nasal.Eosinophil.Count + Nasal.Squamous.Count + Nasal.Epithelial.Count + Viral.Type.at.Visit2, data=nDesignAB)
remIndex<-which(!(rownames(nDesignAB) %in% rownames(curMM)))
length(remIndex)
 
corfitSqu<-duplicateCorrelation(nVoomSquAB[,-remIndex], curMM, block=nDesignAB$Subject.Identifier.for.the.Study[-remIndex])
corfitSqu$consensus
  
fitSqu<-lmFit(nVoomSquAB[,-remIndex], curMM, block=nDesignAB$Subject.Identifier.for.the.Study[-remIndex], correlation=corfitSqu$consensus)
fitSqu<-eBayes(fitSqu)

ttSqu<-topTable(fitSqu, coef=2, number=nrow(nVoomSquAB), sort.by="p")

ttSqu<-addSymbol(ttSqu, resultsBio)
write.csv(ttSqu, file=file.path(resultsDir, "nasal_geneLevel_topTable_Squamous.csv"))


## Unassigned
matchIndex<-match(assignGS$ensemblID[which(assignGS$cellType=="unassigned")], rownames(nasalVoom))
sum(is.na(matchIndex))
matchIndex<-matchIndex[-which(is.na(matchIndex))]
nasalVoomUn<-nasalVoom[matchIndex,]
dim(nasalVoomUn)

nVoomUnAB<-nasalVoomUn[,which(nasalDesign$Visit %in% c("Visit a","Visit b"))]
all(nDesignAB$library.sampleId==colnames(nVoomUnAB))

curMM<-model.matrix(~Case.or.Control.Status.Original + Visit + libCounts + Nasal.Lymphocyte.Count + Nasal.Macrophage.Count + Nasal.Eosinophil.Count + Nasal.Squamous.Count + Nasal.Epithelial.Count + Viral.Type.at.Visit2, data=nDesignAB)
remIndex<-which(!(rownames(nDesignAB) %in% rownames(curMM)))
length(remIndex)
 
corfitUn<-duplicateCorrelation(nVoomUnAB[,-remIndex], curMM, block=nDesignAB$Subject.Identifier.for.the.Study[-remIndex])
corfitUn$consensus
  
fitUn<-lmFit(nVoomUnAB[,-remIndex], curMM, block=nDesignAB$Subject.Identifier.for.the.Study[-remIndex], correlation=corfitUn$consensus)
fitUn<-eBayes(fitUn)

ttUn<-topTable(fitUn, coef=2, number=nrow(nVoomUnAB), sort.by="p")

ttUn<-addSymbol(ttUn, resultsBio)
write.csv(ttUn, file=file.path(resultsDir, "nasal_geneLevel_topTable_Unassigned.csv"))

```

## Venn Diagram

```{r venn}

# already loaded if following the R markdown
# ttUn<-read.csv(file=file.path(resultsDir, "nasal_geneLevel_topTable_Unassigned.csv"), row.names=1)
# ttSqu<-read.csv(file=file.path(resultsDir, "nasal_geneLevel_topTable_Squamous.csv"), row.names=1)
# ttMac<-read.csv(file=file.path(resultsDir, "nasal_geneLevel_topTable_Macrophage.csv"), row.names=1)
# ttLym<-read.csv(file=file.path(resultsDir, "nasal_geneLevel_topTable_Lymphocyte.csv"), row.names=1)
# ttEpi<-read.csv(file=file.path(resultsDir, "nasal_geneLevel_topTable_Epithelial.csv"), row.names=1)
# ttEos<-read.csv(file=file.path(resultsDir, "nasal_geneLevel_topTable_Eosinophil.csv"), row.names=1)
# ttNeu<-read.csv(file=file.path(resultsDir, "nasal_geneLevel_topTable_Neutrophil.csv"), row.names=1)

sum(ttUn$adj.P.Val < 0.05) # 678
sum(ttSqu$adj.P.Val < 0.05) # 332
sum(ttMac$adj.P.Val < 0.05) # 191
sum(ttLym$adj.P.Val < 0.05) # 335
sum(ttEpi$adj.P.Val < 0.05) # 159
sum(ttEos$adj.P.Val < 0.05) # 101
sum(ttNeu$adj.P.Val < 0.05) # 0

# look at whether the genes are in the same direction for sig genes by cell type
table(ttUn$logFC[which(ttUn$adj.P.Val < 0.05)] > 0) # unassigned are really split in half
table(ttSqu$logFC[which(ttSqu$adj.P.Val < 0.05)] > 0) # pos
table(ttMac$logFC[which(ttMac$adj.P.Val < 0.05)] > 0) # pos
table(ttLym$logFC[which(ttLym$adj.P.Val < 0.05)] > 0) # neg
table(ttEpi$logFC[which(ttEpi$adj.P.Val < 0.05)] > 0) # pos
table(ttEos$logFC[which(ttEos$adj.P.Val < 0.05)] > 0) # pos


# is there overlap between these?
# no overlap in unassigned
sum(rownames(ttUn)[which(ttUn$adj.P.Val < 0.05)] %in% rownames(ttSqu)[which(ttSqu$adj.P.Val < 0.05)]) # 0
sum(rownames(ttUn)[which(ttUn$adj.P.Val < 0.05)] %in% rownames(ttMac)[which(ttMac$adj.P.Val < 0.05)]) # 0
sum(rownames(ttUn)[which(ttUn$adj.P.Val < 0.05)] %in% rownames(ttLym)[which(ttLym$adj.P.Val < 0.05)]) # 0
sum(rownames(ttUn)[which(ttUn$adj.P.Val < 0.05)] %in% rownames(ttEpi)[which(ttEpi$adj.P.Val < 0.05)]) # 0
sum(rownames(ttUn)[which(ttUn$adj.P.Val < 0.05)] %in% rownames(ttEos)[which(ttEos$adj.P.Val < 0.05)]) # 0

sum(rownames(ttSqu)[which(ttSqu$adj.P.Val < 0.05)] %in% rownames(ttMac)[which(ttMac$adj.P.Val < 0.05)]) # 3
sum(rownames(ttSqu)[which(ttSqu$adj.P.Val < 0.05)] %in% rownames(ttLym)[which(ttLym$adj.P.Val < 0.05)]) # 0
sum(rownames(ttSqu)[which(ttSqu$adj.P.Val < 0.05)] %in% rownames(ttEpi)[which(ttEpi$adj.P.Val < 0.05)]) # 103
sum(rownames(ttSqu)[which(ttSqu$adj.P.Val < 0.05)] %in% rownames(ttEos)[which(ttEos$adj.P.Val < 0.05)]) # 14

sum(rownames(ttMac)[which(ttMac$adj.P.Val < 0.05)] %in% rownames(ttLym)[which(ttLym$adj.P.Val < 0.05)]) # 22
sum(rownames(ttMac)[which(ttMac$adj.P.Val < 0.05)] %in% rownames(ttEpi)[which(ttEpi$adj.P.Val < 0.05)]) # 2
sum(rownames(ttMac)[which(ttMac$adj.P.Val < 0.05)] %in% rownames(ttEos)[which(ttEos$adj.P.Val < 0.05)]) # 5

sum(rownames(ttLym)[which(ttLym$adj.P.Val < 0.05)] %in% rownames(ttEpi)[which(ttEpi$adj.P.Val < 0.05)]) # 0
sum(rownames(ttLym)[which(ttLym$adj.P.Val < 0.05)] %in% rownames(ttEos)[which(ttEos$adj.P.Val < 0.05)]) # 0

sum(rownames(ttEpi)[which(ttEpi$adj.P.Val < 0.05)] %in% rownames(ttEos)[which(ttEos$adj.P.Val < 0.05)]) # 6

# have 5 cell types to look - nothing was sig for neutrophil
allGenes<-unique(c(rownames(ttSqu), rownames(ttMac), rownames(ttLym), rownames(ttEpi), rownames(ttEos)))
binSqu<-rep(0, length(allGenes))
binSqu[match(rownames(ttSqu)[which(ttSqu$adj.P.Val < 0.05)], allGenes)]<-1
table(binSqu)
binMac<-rep(0, length(allGenes))
binMac[match(rownames(ttMac)[which(ttMac$adj.P.Val < 0.05)], allGenes)]<-1
table(binMac)
binLym<-rep(0, length(allGenes))
binLym[match(rownames(ttLym)[which(ttLym$adj.P.Val < 0.05)], allGenes)]<-1
table(binLym)
binEpi<-rep(0, length(allGenes))
binEpi[match(rownames(ttEpi)[which(ttEpi$adj.P.Val < 0.05)], allGenes)]<-1
table(binEpi)
binEos<-rep(0, length(allGenes))
binEos[match(rownames(ttEos)[which(ttEos$adj.P.Val < 0.05)], allGenes)]<-1
table(binEos)

binCell<-cbind(binSqu, binMac, binLym, binEpi, binEos)
rownames(binCell)<-allGenes
colnames(binCell)<-c("Squa","Mac","Lym","Epi","Eos")

vennDiagram(binCell, col=c("blue","green","orange","yellow","red"))

sigGenesByCellType<-c(rownames(binCell)[which(apply(binCell, 1, sum) > 0)], rownames(ttUn)[which(ttUn$adj.P.Val < 0.05)])

```

## Full Set

```{r fullSet}

nDesignAB<-nasalDesign[which(nasalDesign$Visit %in% c("Visit a","Visit b")),]
nVoomAB<-nasalVoom[,which(nasalDesign$Visit %in% c("Visit a","Visit b"))]
all(nDesignAB$library.sampleId==colnames(nVoomAB))

nDesignAB$Case.or.Control.Status.Original<-factor(as.character(nDesignAB$Case.or.Control.Status.Original), levels=c("Control","Case"))
nDesignAB$Visit<-factor(as.character(nDesignAB$Visit), levels=c("Visit a","Visit b"))

curMM<-model.matrix(~Case.or.Control.Status.Original + Visit + libCounts + Nasal.Lymphocyte.Count + Nasal.Macrophage.Count + Nasal.Eosinophil.Count + Nasal.Squamous.Count + Nasal.Epithelial.Count + Viral.Type.at.Visit2, data=nDesignAB)
remIndex<-which(!(rownames(nDesignAB) %in% rownames(curMM)))
length(remIndex)
 
corfit<-duplicateCorrelation(nVoomAB[,-remIndex], curMM, block=nDesignAB$Subject.Identifier.for.the.Study[-remIndex])
corfit$consensus
  
fitAll<-lmFit(nVoomAB[,-remIndex], curMM, block=nDesignAB$Subject.Identifier.for.the.Study[-remIndex], correlation=corfit$consensus)
fitAll<-eBayes(fitAll)

ttAll<-topTable(fitAll, coef=2, number=nrow(nVoomAB), sort.by="p")
ttAll<-addSymbol(ttAll, resultsBio)
write.csv(ttAll, file=file.path(resultsDir, "nasal_geneLevel_topTable_allGenes.csv"))
#ttAll<-read.csv(file="/Users/ewhalen/Box Sync/Projects/ICAC/MUPPITS/nasal_Combine4Phases/geneLevel/topTable_allGenes.csv", row.names=1)
table(rownames(ttAll)[which(ttAll$adj.P.Val < 0.05)] %in% sigGenesByCellType)


# make longitudinal plots of top 210 genes 

library(ggplot2)

longPlot<-function(geneName, nVoomAB, nDesignAB, log=TRUE, geneGS)
{
  dataToPlot<-as.data.frame(cbind(as.vector(as.matrix(nVoomAB[which(rownames(nVoomAB)==geneName),])), as.character(nDesignAB$Case.or.Control.Status.Original), nDesignAB$Days.between.Cold.and.Visit, nDesignAB$Days.between.Cold.and.Exacerbation, as.character(nDesignAB$Visit), nDesignAB$Days.between.Visit.and.CSteroid.Use))
  dim(dataToPlot)
  colnames(dataToPlot)<-c("Exp","Status","Days","DaysBetweenColdExac","Visit","DaysBetweenVisitAndCS")
  dataToPlot$Exp<-as.numeric(as.character(dataToPlot$Exp))
  dataToPlot$Days<-as.numeric(as.character(dataToPlot$Days))
  dataToPlot$Status<-factor(as.character(dataToPlot$Status), levels=c("Control","Case"))
  dataToPlot$DaysBetweenColdExac<-as.numeric(as.character(dataToPlot$DaysBetweenColdExac))
  dataToPlot$Visit<-as.character(dataToPlot$Visit)
  dataToPlot$DaysBetweenVisitAndCS<-as.numeric(as.character(dataToPlot$DaysBetweenVisitAndCS))

  dataToPlot$ExacYet<-"N"
  dataToPlot$ExacYet[dataToPlot$Days > dataToPlot$DaysBetweenColdExac]<-"Y"
  table(dataToPlot$Status, dataToPlot$ExacYet)
  dataToPlot$StatusNew<-as.character(dataToPlot$Status)
  dataToPlot$StatusNew[which(dataToPlot$Status=="Case" & dataToPlot$ExacYet=="Y")]<-"Case on CSteroid"
  table(dataToPlot$StatusNew)
  
  # bin different days post-cold
  # combine days 0 and 1
  # combine days 6, 7, and 12
  # consider combining days 3-4?
  dataToPlot$DaysBin<-as.character(dataToPlot$Days)
  dataToPlot$DaysBin[which(dataToPlot$Days %in% c(0,1))]<-"0-1"
  dataToPlot$DaysBin[which(dataToPlot$Days %in% c(6,7,12))]<-"6+"
  if (any(dataToPlot$Days == -1))
    dataToPlot$DaysBin<-factor(dataToPlot$DaysBin, levels=c("-1","0-1","2","3","4","5","6+"))
  else
    dataToPlot$DaysBin<-factor(dataToPlot$DaysBin, levels=c("0-1","2","3","4","5","6+"))
  
#  # remove days post-cold at 12
#  if (any(dataToPlot$Days==12))
#    dataToPlotSub<-dataToPlot[-which(dataToPlot$Days==12),]
#  else
#    dataToPlotSub<-dataToPlot
  dataToPlotSub<-dataToPlot
  
#  ggplot(dataToPlotSub, aes(x=Days, y=Exp, color=Status))+geom_point()+geom_smooth() + xlab("Days Post-Cold") +ggtitle(modName) + ylab("log2(exp)")

  # color case points by whether they've experienced exacerbation yet
  if (log==TRUE)
  {
    if (any(dataToPlotSub$Days==-1))
      ggplot(dataToPlotSub, aes(x=as.numeric(DaysBin), y=Exp, color=StatusNew))+geom_point()+geom_smooth(method="loess",span=1.5) + xlab("Days Post-Cold") +ggtitle(geneGS) + ylab("log2(exp)") + scale_x_continuous(breaks=1:7, labels=levels(dataToPlotSub$DaysBin)) + ylim(0, max(dataToPlotSub$Exp)) + theme_bw() + scale_color_manual(values=c("red","black"))
    else
      ggplot(dataToPlotSub, aes(x=as.numeric(DaysBin), y=Exp, color=StatusNew))+geom_point()+geom_smooth(method="loess",span=1.5) + xlab("Days Post-Cold") +ggtitle(geneGS) + ylab("log2(exp)") + scale_x_continuous(breaks=1:6, labels=levels(dataToPlotSub$DaysBin)) + ylim(0, max(dataToPlotSub$Exp)) + theme_bw() + scale_color_manual(values=c("red","black"))
  }
  else
  {
    # show expression on original scale
    if (any(dataToPlotSub$Days==-1))
      ggplot(dataToPlotSub, aes(x=as.numeric(DaysBin), y=2^Exp, color=StatusNew)) + geom_point() + geom_smooth(method="loess",span=1.5, aes(fill=StatusNew)) + xlab("Days Post-Cold") +ggtitle(geneGS) + ylab("Normalized Expression") + scale_x_continuous(breaks=1:7, labels=levels(dataToPlotSub$DaysBin)) + ylim(0, max(2^dataToPlotSub$Exp)) + theme_bw() + scale_color_manual(values=c("red","black")) + scale_fill_manual(values=c("pink","gray")) + guides(fill=guide_legend(override.aes = list(fill="white",size=1.2)))
    
    else
      ggplot(dataToPlotSub, aes(x=as.numeric(DaysBin), y=2^Exp, color=StatusNew))+geom_point()+geom_smooth(method="loess",span=1.5) + xlab("Days Post-Cold") +ggtitle(geneGS) + ylab("Normalized Expression") + scale_x_continuous(breaks=1:6, labels=levels(dataToPlotSub$DaysBin)) + ylim(0, max(2^dataToPlotSub$Exp)) + theme_bw() + scale_color_manual(values=c("red","black"))
  }
}

# remove batch effect and include visit 0
# need to set up case/control status for visit 0
uniIDs<-unique(as.character(nasalDesign$Subject.Identifier.for.the.Study))
nasalDesign$Case.or.Control.Status.Original<-as.character(nasalDesign$Case.or.Control.Status.Original)
for (i in 1:length(uniIDs))
{
  curID<-uniIDs[i]
  curIndex<-which(nasalDesign$Subject.Identifier.for.the.Study==curID)
  curIndex0<-which(nasalDesign$Subject.Identifier.for.the.Study==curID & nasalDesign$Visit=="Visit 0")
  if (length(curIndex0)==1)
  {
    if ("Case" %in% nasalDesign$Case.or.Control.Status.Original[curIndex])
      nasalDesign$Case.or.Control.Status.Original[curIndex0]<-"Case"
    else
      nasalDesign$Case.or.Control.Status.Original[curIndex0]<-"Control"
  }
}
table(nasalDesign$Case.or.Control.Status.Original)

remIndex<-unique(c(which(is.na(nasalDesign$Nasal.Lymphocyte.Count)), which(is.na(nasalDesign$Nasal.Macrophage.Count)), which(is.na(nasalDesign$Nasal.Eosinophil.Count)), which(is.na(nasalDesign$Nasal.Epithelial.Count)), which(is.na(nasalDesign$Nasal.Squamous.Count)), which(is.na(nasalDesign$libCounts)), which(is.na(nasalDesign$Viral.Type.at.Visit2))))
length(remIndex) # lost 11 out of 347 samples (already removed cases with steroids)
dim(nasalDesign)

rbeMM<-model.matrix(~ Nasal.Lymphocyte.Count + Nasal.Eosinophil.Count + Nasal.Macrophage.Count + Nasal.Epithelial.Count +  Nasal.Squamous.Count + libCounts, data=nasalDesign[-remIndex,])
dim(rbeMM)
rbeMM[1:3,]

keepmm<-model.matrix(~Visit + Case.or.Control.Status.Original + Viral.Type.at.Visit2, data=nasalDesign[-remIndex,])
dim(keepmm)
keepmm[1:3,]

# remove batch effect at voom level
nasalVoomRbe<-removeBatchEffect(nasalVoom[,-remIndex], covariates=rbeMM[,-1], design=keepmm)
nasalDesignSub<-nasalDesign[-remIndex,]
nasalVoomRbeN<-as.matrix(nasalVoom[,-remIndex])

all(nasalDesignSub$library.sampleId==colnames(nasalVoomRbe))
all(nasalDesignSub$library.sampleId==colnames(nasalVoomRbeN))


nasalDesign2<-nasalDesignSub
nasalDesign2$Days.between.Cold.and.Visit[which(nasalDesign2$Visit=="Visit 0")]<--1
table(nasalDesign2$Days.between.Cold.and.Visit)
table(nasalDesign2$Case.or.Control.Status.Original)


for (i in 1:210)
{
  curGene<-rownames(ttAll)[i]
  curGS<-ttAll$hgnc_symbol[i]
  png(file=paste(file.path(resultsDir, "nasal_geneLevel_longitudinal_"), curGS, ".png", sep=""), units="in", width=6, height=5, res=300, pointsize=9)
  g1<-longPlot(geneName=curGene, nasalVoomRbe, nasalDesign2, log=FALSE, geneGS=curGS)
  print(g1)
  dev.off()
}

```

## Make Gene Set Plots

```{r geneSetPlots}

uniIDs<-unique(as.character(nasalDesign$Subject.Identifier.for.the.Study))
nasalDesign$Case.or.Control.Status.Original<-as.character(nasalDesign$Case.or.Control.Status.Original)
for (i in 1:length(uniIDs))
{
  curID<-uniIDs[i]
  curIndex<-which(nasalDesign$Subject.Identifier.for.the.Study==curID)
  curIndex0<-which(nasalDesign$Subject.Identifier.for.the.Study==curID & nasalDesign$Visit=="Visit 0")
  if (length(curIndex0)==1)
  {
    if ("Case" %in% nasalDesign$Case.or.Control.Status.Original[curIndex])
      nasalDesign$Case.or.Control.Status.Original[curIndex0]<-"Case"
    else
      nasalDesign$Case.or.Control.Status.Original[curIndex0]<-"Control"
  }
}
table(nasalDesign$Case.or.Control.Status.Original)

nasalDesign$Days.between.Cold.and.Visit[which(nasalDesign$Visit=="Visit 0")]<--1

remIndex<-unique(c(which(is.na(nasalDesign$Nasal.Lymphocyte.Count)), which(is.na(nasalDesign$Nasal.Macrophage.Count)), which(is.na(nasalDesign$Nasal.Eosinophil.Count)), which(is.na(nasalDesign$Nasal.Epithelial.Count)), which(is.na(nasalDesign$Nasal.Squamous.Count)), which(is.na(nasalDesign$libCounts)), which(is.na(nasalDesign$Viral.Type.at.Visit2))))
length(remIndex) # lost 11 out of 347 samples
dim(nasalDesign)

rbeMM<-model.matrix(~ Nasal.Lymphocyte.Count + Nasal.Eosinophil.Count + Nasal.Macrophage.Count + Nasal.Epithelial.Count +  Nasal.Squamous.Count + libCounts, data=nasalDesign[-remIndex,])
dim(rbeMM)
rbeMM[1:3,]

keepmm<-model.matrix(~Visit + Case.or.Control.Status.Original + Viral.Type.at.Visit2, data=nasalDesign[-remIndex,])
dim(keepmm)
keepmm[1:3,]

# remove batch effect at voom level
nasalGSrbe<-removeBatchEffect(nasalGS[,-remIndex], covariates=rbeMM[,-1], design=keepmm)
nasalGSrbeN<-as.matrix(nasalGS[,-remIndex])

nasalDesignSub<-nasalDesign[-remIndex,]
all(nasalDesignSub$library.sampleId==colnames(nasalGSrbe))
all(nasalDesignSub$library.sampleId==colnames(nasalGSrbeN))

longPlotMod<-function(modName="eos3", nasalGS, nasalDesign, log=TRUE, points=TRUE, setSpan=0.75)
{
  dataToPlot<-as.data.frame(cbind(as.vector(as.matrix(nasalGS[which(rownames(nasalGS)==modName),])), as.character(nasalDesign$Case.or.Control.Status.Original), nasalDesign$Days.between.Cold.and.Visit, nasalDesign$Days.between.Cold.and.Exacerbation, as.character(nasalDesign$Visit), nasalDesign$Days.between.Visit.and.CSteroid.Use))
  dim(dataToPlot)
  colnames(dataToPlot)<-c("Exp","Status","Days","DaysBetweenColdExac","Visit","DaysBetweenVisitAndCS")
  dataToPlot$Exp<-as.numeric(as.character(dataToPlot$Exp))
  dataToPlot$Days<-as.numeric(as.character(dataToPlot$Days))
  dataToPlot$Status<-factor(as.character(dataToPlot$Status), levels=c("Control","Case"))
  dataToPlot$DaysBetweenColdExac<-as.numeric(as.character(dataToPlot$DaysBetweenColdExac))
  dataToPlot$Visit<-as.character(dataToPlot$Visit)
  dataToPlot$DaysBetweenVisitAndCS<-as.numeric(as.character(dataToPlot$DaysBetweenVisitAndCS))

  dataToPlot$ExacYet<-"N"
  dataToPlot$ExacYet[dataToPlot$Days > dataToPlot$DaysBetweenColdExac]<-"Y"
  table(dataToPlot$Status, dataToPlot$ExacYet)
  dataToPlot$StatusNew<-as.character(dataToPlot$Status)
  dataToPlot$StatusNew[which(dataToPlot$Status=="Case" & dataToPlot$ExacYet=="Y")]<-"Case on CSteroid"
  table(dataToPlot$StatusNew)
  
  # bin different days post-cold
  # combine days 0 and 1 for both
  # combine days 5, 6, 7, and 12 for controls
  # combine days 4 and 5 for cases
  dataToPlot$DaysBin<-as.character(dataToPlot$Days)
  dataToPlot$DaysBin[which(dataToPlot$Days %in% c(0,1))]<-"0.5"
  dataToPlot$DaysBin[which(dataToPlot$Days %in% c(5,6,7,12))]<-"5"
  dataToPlot$DaysBin[which(dataToPlot$Days %in% c(4,5) & dataToPlot$Status=="Case")]<-"5"

  # color case points by whether they've experienced exacerbation yet
  if (log==TRUE)
  {
    if (any(dataToPlot$Days==-1))
      ggplot(dataToPlot, aes(x=as.numeric(DaysBin), y=Exp, color=StatusNew))+geom_point()+geom_smooth(method="loess",span=setSpan) + xlab("Days Post-Cold") +ggtitle(modName) + ylab("log2(exp)") + scale_x_continuous(breaks=c(-1:5), labels=c("V0","0","1","2","3","4","5+")) + ylim(range(dataToPlot$Exp)) + theme_bw() + scale_color_manual(values=c("red","black"))
    else
      ggplot(dataToPlot, aes(x=as.numeric(DaysBin), y=Exp, color=StatusNew))+geom_point()+geom_smooth(method="loess",span=setSpan) + xlab("Days Post-Cold") +ggtitle(modName) + ylab("log2(exp)") + scale_x_continuous(breaks=1:6, labels=c("0","1","2","3","4","5")) + ylim(range(dataToPlot$Exp)) + theme_bw() + scale_color_manual(values=c("red","black"))
  }
  else
  {
    # show expression on original scale
    if (any(dataToPlot$Days==-1))
#      ggplot(dataToPlot, aes(x=as.numeric(DaysBin), y=2^Exp, color=StatusNew)) + geom_point() + geom_smooth(method="loess",span=0.75, aes(fill=StatusNew)) + xlab("Days Post-Cold") +ggtitle(modName) + ylab("Normalized Expression") + scale_x_continuous(breaks=c(-1:5), labels=c("V0","0","1","2","3","4","5+")) + ylim(0, max(2^dataToPlot$Exp)) + theme_bw() + scale_color_manual(values=c("red","black")) + scale_fill_manual(values=c("pink","gray")) + guides(fill=guide_legend(override.aes = list(fill="white",size=1.2)))
      ggplot(dataToPlot, aes(x=as.numeric(DaysBin), y=2^Exp, color=StatusNew)) + geom_smooth(method="loess",span=setSpan, aes(fill=StatusNew)) + xlab("Days Post-Cold") +ggtitle(modName) + ylab("Normalized Expression") + scale_x_continuous(breaks=c(-1:5), labels=c("V0","0","1","2","3","4","5+")) + theme_bw() + scale_color_manual(values=c("red","black")) + scale_fill_manual(values=c("pink","gray")) + guides(fill=guide_legend(override.aes = list(fill="white",size=1.2)))
    else
      ggplot(dataToPlot, aes(x=as.numeric(DaysBin), y=2^Exp, color=StatusNew))+geom_point()+geom_smooth(method="loess",span=setSpan) + xlab("Days Post-Cold") +ggtitle(modName) + ylab("Normalized Expression") + scale_x_continuous(breaks=1:6, labels=c("0","1","2","3","4","5")) + ylim(0, max(2^dataToPlot$Exp)) + theme_bw() + scale_color_manual(values=c("red","black"))
  }
}

g1<-longPlotMod(modName="epi1", nasalGSrbe, nasalDesignSub, log=FALSE, points=TRUE)
g1

remMods<-c("neut0","lymp0","eos0","mac0","epi0","squa0","unma0")
nasalGSrbeOrig<-nasalGSrbe
nasalGSrbe<-nasalGSrbe[-which(rownames(nasalGSrbe) %in% remMods),]
nasalGSrbeN<-nasalGSrbeN[-which(rownames(nasalGSrbeN) %in% remMods),]

for (i in 1:nrow(nasalGSrbe))
{
  curMod<-rownames(nasalGSrbe)[i]
  png(file=paste(file.path(resultsDir, "nasal_longitudinal_loess_modPlots_allVisits_noPoints_"), curMod, ".png", sep=""), units="in", width=6, height=5, res=300, pointsize=9)
  g1<-longPlotMod(modName=curMod,nasalGSrbe, nasalDesignSub, log=FALSE)
  print(g1)
  dev.off()
#  print(i)
}

for (i in 1:nrow(nasalGSrbe))
{
  curMod<-rownames(nasalGSrbe)[i]
  png(file=paste(file.path(resultsDir, "nasal_longitudinal_loess_modPlots_allVisits_noPoints_span1.5_"), curMod, ".png", sep=""), units="in", width=6, height=5, res=300, pointsize=9)
  g1<-longPlotMod(modName=curMod,nasalGSrbe, nasalDesignSub, log=FALSE,setSpan = 1.5)
  print(g1)
  dev.off()
#  print(i)
}

# 1/12/19 make plots using svg file type
for (i in 1:nrow(nasalGSrbe))
{
  curMod<-rownames(nasalGSrbe)[i]
  svg(file=paste(file.path(resultsDir, "nasal_longitudinal_loess_modPlots_allVisits_noPoints_span1.5_"), curMod, ".svg", sep=""))
  g1<-longPlotMod(modName=curMod,nasalGSrbe, nasalDesignSub, log=FALSE,setSpan = 1.5)
  print(g1)
  dev.off()
#  print(i)
}

# 9/28/18
for (i in 1:nrow(nasalGSrbeN))
{
  curMod<-rownames(nasalGSrbeN)[i]
  png(file=paste(file.path(resultsDir, "nasal_longitudinal_loess_modPlots_allVisits_noPoints_span1.5_notCorrectedForCellCount_"), curMod, ".png", sep=""), units="in", width=6, height=5, res=300, pointsize=9)
  g1<-longPlotMod(modName=curMod, nasalGSrbeN, nasalDesignSub, log=FALSE, setSpan = 1.5)
  print(g1)
  dev.off()
#  print(i)
}


# 4/10/18 test significance
library(splines)

# should probably bin days between cold and visit like it is in the plot
posLoessPvals<-c()
for (i in 1:nrow(nasalGSrbe))
{
  fit1<-lm(nasalGSrbe[i,] ~ bs(nasalDesignSub$Days.between.Cold.and.Visit, degree=2))
  fit2<-lm(nasalGSrbe[i,] ~ bs(nasalDesignSub$Days.between.Cold.and.Visit, degree=2) + nasalDesignSub$Case.or.Control.Status.Original)
  posLoessPvals<-c(posLoessPvals, anova(fit2, fit1)$Pr[2])
}
posLoessFDR<-p.adjust(posLoessPvals, method="fdr")
rownames(nasalGSrbe)[which(posLoessFDR < 0.05)]

nasalDesignSub$DaysBin<-as.character(nasalDesignSub$Days.between.Cold.and.Visit)
nasalDesignSub$DaysBin[which(nasalDesignSub$Days.between.Cold.and.Visit %in% c(0,1))]<-"0.5"
nasalDesignSub$DaysBin[which(nasalDesignSub$Days.between.Cold.and.Visit %in% c(5,6,7,12))]<-"5"
nasalDesignSub$DaysBin[which(nasalDesignSub$Days.between.Cold.and.Visit %in% c(4,5) & nasalDesignSub$Case.or.Control.Status.Original=="Case")]<-"5"
nasalDesignSub$DaysBin<-as.numeric(nasalDesignSub$DaysBin)

posLoessPvals2<-c()
for (i in 1:nrow(nasalGSrbe))
{
  fit1<-lm(nasalGSrbe[i,] ~ bs(nasalDesignSub$DaysBin, degree=2))
  fit2<-lm(nasalGSrbe[i,] ~ bs(nasalDesignSub$DaysBin, degree=2) + nasalDesignSub$Case.or.Control.Status.Original)
  posLoessPvals2<-c(posLoessPvals2, anova(fit2, fit1)$Pr[2])
}
posLoessFDR2<-p.adjust(posLoessPvals2, method="fdr")
rownames(nasalGSrbe)[which(posLoessFDR2 < 0.05)]

# write to file
allStat<-as.data.frame(cbind(rownames(nasalGSrbe), posLoessPvals2, posLoessFDR2))
colnames(allStat)<-c("module","pval","FDR")
write.csv(allStat, file=file.path(resultsDir, "loess_modPlots_allVisits_noPoints_span1.5_module_Significance_for_Case_V_Control_Fig4A.csv"), row.names=FALSE)



# make a few specifically with limits
png(file=paste(file.path(resultsDir, "nasal_longitudinal_loess_modPlots_allVisits_noPoints_"),"epi1",".png",sep=""), units="in", width=6, height=5, res=300, pointsize=9)
g1<-longPlotMod(modName="epi1", nasalGSrbe, nasalDesignSub, log=FALSE, points=TRUE)
g1+ coord_cartesian(ylim = c(0,3.5))
dev.off()

png(file=paste(file.path(resultsDir, "nasal_longitudinal_loess_modPlots_allVisits_noPoints_"),"eos3",".png",sep=""), units="in", width=6, height=5, res=300, pointsize=9)
g1<-longPlotMod(modName="eos3", nasalGSrbe, nasalDesignSub, log=FALSE, points=TRUE)
g1+ coord_cartesian(ylim = c(0,4.5))
dev.off()

png(file=paste(file.path(resultsDir, "nasal_longitudinal_loess_modPlots_allVisits_noPoints_"),"unma11",".png",sep=""), units="in", width=6, height=5, res=300, pointsize=9)
g1<-longPlotMod(modName="unma11", nasalGSrbe, nasalDesignSub, log=FALSE, points=TRUE)
g1+ coord_cartesian(ylim = c(0,100))
dev.off()

png(file=paste(file.path(resultsDir, "nasal_longitudinal_loess_modPlots_allVisits_noPoints_"),"unma23",".png",sep=""), units="in", width=6, height=5, res=300, pointsize=9)
g1<-longPlotMod(modName="unma23", nasalGSrbe, nasalDesignSub, log=FALSE, points=TRUE)
g1+ coord_cartesian(ylim = c(0,28))
dev.off()

png(file=paste(file.path(resultsDir, "nasal_longitudinal_loess_modPlots_allVisits_noPoints_"),"unma5",".png",sep=""), units="in", width=6, height=5, res=300, pointsize=9)
g1<-longPlotMod(modName="unma5", nasalGSrbe, nasalDesignSub, log=FALSE, points=TRUE)
g1+ coord_cartesian(ylim = c(0,1.5))
dev.off()

png(file=paste(file.path(resultsDir, "nasal_longitudinal_loess_modPlots_allVisits_noPoints_"),"unma13",".png",sep=""), units="in", width=6, height=5, res=300, pointsize=9)
g1<-longPlotMod(modName="unma13", nasalGSrbe, nasalDesignSub, log=FALSE, points=TRUE)
g1+ coord_cartesian(ylim = c(0,1.25))
dev.off()

```

## Cell Counts

```{r cellCounts}

longPlotCellCounts<-function(cellName="Nasal.Neutrophil.Count", nasalDesign, points=TRUE, plotTitle="Nasal Neutrophil Count", ylimLow=0, ylimUp=100)
{
  dataToPlot<-as.data.frame(cbind(as.vector(as.matrix(nasalDesign[,which(colnames(nasalDesign)==cellName)])), as.character(nasalDesign$Case.or.Control.Status.Original), nasalDesign$Days.between.Cold.and.Visit, nasalDesign$Days.between.Cold.and.Exacerbation, as.character(nasalDesign$Visit), nasalDesign$Days.between.Visit.and.CSteroid.Use))
  dim(dataToPlot)
  colnames(dataToPlot)<-c("CellCount","Status","Days","DaysBetweenColdExac","Visit","DaysBetweenVisitAndCS")
  dataToPlot$CellCount<-as.numeric(as.character(dataToPlot$CellCount))
  dataToPlot$Days<-as.numeric(as.character(dataToPlot$Days))
  dataToPlot$Status<-factor(as.character(dataToPlot$Status), levels=c("Control","Case"))
  dataToPlot$DaysBetweenColdExac<-as.numeric(as.character(dataToPlot$DaysBetweenColdExac))
  dataToPlot$Visit<-as.character(dataToPlot$Visit)
  dataToPlot$DaysBetweenVisitAndCS<-as.numeric(as.character(dataToPlot$DaysBetweenVisitAndCS))

  dataToPlot$ExacYet<-"N"
  dataToPlot$ExacYet[dataToPlot$Days > dataToPlot$DaysBetweenColdExac]<-"Y"
  table(dataToPlot$Status, dataToPlot$ExacYet)
  dataToPlot$StatusNew<-as.character(dataToPlot$Status)
  dataToPlot$StatusNew[which(dataToPlot$Status=="Case" & dataToPlot$ExacYet=="Y")]<-"Case on CSteroid"
  table(dataToPlot$StatusNew)
  
  # bin different days post-cold
  # combine days 0 and 1 for both
  # combine days 5, 6, 7, and 12 for controls
  # combine days 4 and 5 for cases
  dataToPlot$DaysBin<-as.character(dataToPlot$Days)
  dataToPlot$DaysBin[which(dataToPlot$Days %in% c(0,1))]<-"0.5"
  dataToPlot$DaysBin[which(dataToPlot$Days %in% c(5,6,7,12))]<-"5"
  dataToPlot$DaysBin[which(dataToPlot$Days %in% c(4,5) & dataToPlot$Status=="Case")]<-"5"

  # color case points by whether they've experienced exacerbation yet
  {
    # show expression on original scale
    if (any(dataToPlot$Days==-1))
#      ggplot(dataToPlot, aes(x=as.numeric(DaysBin), y=CellCount, color=StatusNew)) + geom_point() + geom_smooth(method="loess",span=0.75, aes(fill=StatusNew)) + xlab("Days Post-Cold") +ggtitle(plotTitle) + ylab("Cell Count") + scale_x_continuous(breaks=c(-1:5), labels=c("V0","0","1","2","3","4","5+")) + ylim(0, max(dataToPlot$CellCount)) + theme_bw() + scale_color_manual(values=c("red","black")) + scale_fill_manual(values=c("pink","gray")) + guides(fill=guide_legend(override.aes = list(fill="white",size=1.2)))
      ggplot(dataToPlot, aes(x=as.numeric(DaysBin), y=CellCount, color=StatusNew)) + geom_smooth(method="loess",span=0.75, aes(fill=StatusNew)) + xlab("Days Post-Cold") +ggtitle(plotTitle) + ylab("Cell Count") + scale_x_continuous(breaks=c(-1:5), labels=c("V0","0","1","2","3","4","5+")) + theme_bw() + scale_color_manual(values=c("red","black")) + scale_fill_manual(values=c("pink","gray")) + guides(fill=guide_legend(override.aes = list(fill="white",size=1.2))) + coord_cartesian(ylim = c(ylimLow,ylimUp))
    else
      ggplot(dataToPlot, aes(x=as.numeric(DaysBin), y=CellCount, color=StatusNew))+geom_point()+geom_smooth(method="loess",span=0.75) + xlab("Days Post-Cold") +ggtitle(plotTitle) + ylab("Cell Count") + scale_x_continuous(breaks=1:6, labels=c("0","1","2","3","4","5")) + ylim(0, max(dataToPlot$CellCount)) + theme_bw() + scale_color_manual(values=c("red","black"))+coord_cartesian(ylim = c(ylimLow,ylimUp))
  }
}

png(file=paste(file.path(resultsDir, "nasal_longitudinal_loess_cellCountPlots_"),"Neutrophil",".png",sep=""), units="in", width=6, height=5, res=300, pointsize=9)
longPlotCellCounts(cellName="Nasal.Neutrophil.Count", nasalDesign, points=TRUE, plotTitle="Nasal Neutrophil Count", ylimLow=0, ylimUp=100)
dev.off()

png(file=paste(file.path(resultsDir, "nasal_longitudinal_loess_cellCountPlots_"),"Lymphocyte",".png",sep=""), units="in", width=6, height=5, res=300, pointsize=9)
longPlotCellCounts(cellName="Nasal.Lymphocyte.Count", nasalDesign, points=TRUE, plotTitle="Nasal Lymphocyte Count", ylimLow=0, ylimUp=10)
dev.off()

png(file=paste(file.path(resultsDir, "nasal_longitudinal_loess_cellCountPlots_"),"Eosinophil",".png",sep=""), units="in", width=6, height=5, res=300, pointsize=9)
longPlotCellCounts(cellName="Nasal.Eosinophil.Count", nasalDesign, points=TRUE, plotTitle="Nasal Eosinophil Count", ylimLow=-1, ylimUp=25)
dev.off()

png(file=paste(file.path(resultsDir, "nasal_longitudinal_loess_cellCountPlots_"),"Macrophage",".png",sep=""), units="in", width=6, height=5, res=300, pointsize=9)
longPlotCellCounts(cellName="Nasal.Macrophage.Count", nasalDesign, points=TRUE, plotTitle="Nasal Macrophage Count", ylimLow=0, ylimUp=10)
dev.off()

png(file=paste(file.path(resultsDir, "nasal_longitudinal_loess_cellCountPlots_"),"WBC",".png",sep=""), units="in", width=6, height=5, res=300, pointsize=9)
longPlotCellCounts(cellName="Nasal.WBC.Count", nasalDesign, points=TRUE, plotTitle="Nasal WBC Count", ylimLow=0, ylimUp=100)
dev.off()

png(file=paste(file.path(resultsDir, "nasal_longitudinal_loess_cellCountPlots_"),"Epithelial",".png",sep=""), units="in", width=6, height=5, res=300, pointsize=9)
longPlotCellCounts(cellName="Nasal.Epithelial.Count", nasalDesign, points=TRUE, plotTitle="Nasal Epithelial Count", ylimLow=0, ylimUp=10)
dev.off()

png(file=paste(file.path(resultsDir, "nasal_longitudinal_loess_cellCountPlots_"),"Squamous",".png",sep=""), units="in", width=6, height=5, res=300, pointsize=9)
longPlotCellCounts(cellName="Nasal.Squamous.Count", nasalDesign, points=TRUE, plotTitle="Nasal Squamous Count", ylimLow=0, ylimUp=50)
dev.off()

png(file=paste(file.path(resultsDir, "nasal_longitudinal_loess_cellCountPlots_"),"Epithelial_Squamous",".png",sep=""), units="in", width=6, height=5, res=300, pointsize=9)
longPlotCellCounts(cellName="Nasal.Epi.Squa.Count", nasalDesign, points=TRUE, plotTitle="Nasal Epithelial+Squamous Count", ylimLow=0, ylimUp=50)
dev.off()

```
